@set allusersprofile=c:\programdata
@set appdata=c:\users\ruala\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-b4563md
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\ruala
@set include=c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\include;c:\program files (x86)\windows kits\10\include\10.0.15063.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.15063.0\shared;c:\program files (x86)\windows kits\10\include\10.0.15063.0\um;c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt
@set lib=c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\10\lib\10.0.15063.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.15063.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\10\unionmetadata\10.0.15063.0\;c:\program files (x86)\windows kits\10\references\10.0.15063.0\;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\ruala\appdata\local
@set logonserver=\\desktop-b4563md
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\professional\msbuild\sdks
@set msbuild_exe_path=x:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set number_of_processors=8
@set onedrive=c:\users\ruala\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\professional\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\professional\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\windows kits\10\bin\10.0.15063.0\x86;c:\program files (x86)\microsoft visual studio\2017\professional\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\professional\common7\tools\;c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\github\github\nativebinaries\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\common files\propellerhead software\rewire\;c:\program files\common files\propellerhead software\rewire\;x:\program files\git\cmd;x:\program files (x86)\putty\;x:\program files (x86)\denemo\usr\bin;c:\users\ruala\appdata\local\microsoft\windowsapps;c:\users\ruala\appdata\local\githubdesktop\bin
@set pathext=.py;.scm;.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\ruala\appdata\local\microsoft\visualstudio\15.0_77d4a864\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 58 stepping 9, genuineintel
@set processor_level=6
@set processor_revision=3a09
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\professional\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\professional
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\ruala\appdata\local\temp
@set tmp=c:\users\ruala\appdata\local\temp
@set ucrtversion=10.0.15063.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-b4563md
@set userdomain_roamingprofile=desktop-b4563md
@set username=ruala
@set userprofile=c:\users\ruala
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\professional\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.10.25017\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\professional\vc\redist\msvc\14.10.25017\
@set visualstudiodir=c:\users\ruala\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio professional 2017
@set visualstudioversion=15.0
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\professional\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.0.26430.15
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\professional\
@set vslang=1033
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.15063.0\;c:\program files (x86)\windows kits\10\references\10.0.15063.0\
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.15063.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.15063.0\
@set windowssdkversion=10.0.15063.0\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\github\github\nativebinaries\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\common files\propellerhead software\rewire\;c:\program files\common files\propellerhead software\rewire\;x:\program files\git\cmd;x:\program files (x86)\putty\;x:\program files (x86)\denemo\usr\bin;c:\users\ruala\appdata\local\microsoft\windowsapps;c:\users\ruala\appdata\local\githubdesktop\bin

@call cl.exe