//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MGen.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MGenTYPE                    130
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_INFO                 310
#define IDD_DIALOG_EDITPARAMS           312
#define IDD_DIALOG_ALGO                 314
#define IDD_DIALOG_MSG                  318
#define IDD_DIALOG_ALGO1                319
#define IDD_DIALOG_MFI                  319
#define IDC_RICHEDIT21                  1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON_HIDDEN               1001
#define IDC_SAVEAS                      1001
#define IDC_BUTTON_SAVEAS               1001
#define IDC_EDIT_ALGO                   1002
#define IDC_COMBO_CONFIG                1004
#define IDC_RICHEDIT_PARAMS             1005
#define IDC_TREE_ALGO                   1006
#define IDC_EDIT_COMMENT                1007
#define IDC_RICHEDIT_CONFIG             1008
#define IDC_BUTTON_EDIT                 1009
#define IDC_STATIC_ALGO                 1010
#define IDC_STATIC_CONFIG               1011
#define IDC_MFCLINK1                    1012
#define IDC_MFCLINK2                    1013
#define IDC_RICHEDIT_MSG                1014
#define IDC_STATIC_VER                  1015
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_OUTPUTWND             32772
#define ID_COMBO_ALGO                   32775
#define ID_BUTTON7                      32784
#define ID_BUTTON8                      32785
#define ID_BUTTON_SETTINGS              32786
#define ID_BUTTON_GEN                   32787
#define ID_BUTTON_PLAY                  32788
#define ID_BUTTON_EXPORT                32789
#define ID_BUTTON_PARAMS                32790
#define ID_BUTTON13                     32791
#define ID_BUTTON_ALGO                  32792
#define ID_COMBO_MIDIOUT                32793
#define ID_COMBO_PARAMS                 32795
#define ID_CHECK_CURVE                  32797
#define ID_BUTTON_EPARAMS               32798
#define ID_CHECK_OUTPUTWND              32799
#define ID_BUTTON_ERULES                32800
#define ID_BUTTON_SETTINGS_EDIT         32801
#define ID_BUTTON_HZOOM_INC             32802
#define ID_BUTTON_ECSV                  32803
#define ID_BUTTON_RELOADALGO            32807
#define ID_BUTTON_SCONFIG               32808
#define ID_BUTTON_RSETTINGS             32809
#define ID_BUTTON_PDF                   32810
#define ID_SPIN_PSPEED                  32811
#define ID_SPIN2                        32812
#define ID_SPIN_ZOOM                    32812
#define ID_BUTTON_EDITALGO              32813
#define ID_BUTTON_EDITINST              32814
#define ID_POPUP_SHOWFULLTEXT           32815
#define ID_POPUP_SHOW                   32816
#define ID_EDIT_SAVELINE                32817
#define ID_POPUP_CLEARALL               32818
#define ID_CLEARALL                     32819
#define ID_BUTTON_HZOOM_DEC             32820
#define ID_BUTTON_OPENMIDI              32821
#define ID_BUTTON_RELOAD_SETTINGS       32822
#define ID_BUTTON_OPENCSV               32823
#define ID_OINFO                        32824
#define ID_OINFO2                       32825
#define ID_OINFO3                       32826
#define ID_OINFO4                       32827
#define ID_OINFO5                       32828
#define ID_OINFO6                       32829
#define ID_CHECK_MARKS                  32831
#define ID_CHECK_TEMPO                  32832
#define ID_CHECK_COMMENTS               32833
#define ID_CHECK_LINING                 32834
#define ID_CHECK_LINES                  32835
#define ID_CHECK_VEL                    32836
#define ID_CHECK_NCOLORS                32837
#define ID_OINFO7                       32839
#define ID_OINFO8                       32840
#define ID_OINFO9                       32841
#define ID_BUTTON_SSTATUS2              32842
#define ID_CHECK_NSR                    32843
#define ID_BUTTON_LY                    32844
#define ID_BUTTON_FOLDER                32845
#define ID_CHECK_GRAPH1                 32846
#define ID_CHECK_SHIFT                  32847
#define ID_CHECK_GRAPH2                 32848
#define ID_CHECK_GRAPH3                 32849
#define ID_CHECK_PROGRESS               32850
#define ID_CHECK_DEBUGEXPECT            32851

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
