include "include/CA2.pl"

# Analysis
#Midi_file = "midi\GenCA2\test-tonicroot.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-last-direct.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-fis-multivoice.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-gis-multivoice.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-tonic-seq.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-overlap.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-2c1-2.mid" # Path and file name  importedof midi file
#Midi_file = "midi\GenCA2\test-2c1.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-vint.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\cp1.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\known-cp2v1.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\cpointer-2c1.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-alterint.mid" # Path and file name of imported midi file
#Midi_file = "midi\temp\2017-08-11-auto 23-36-05.mid"
#Midi_file = "midi\GenCA2\test-sus.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-end.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp3.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-rpos.mid" # Path and file name of imported midi file
#Midi_file = "midi\good-cp4.mid" # Path and file name of imported midi file
#Midi_file = "midi\temp\temp.mid"
#Midi_file = "midi\GenCA2\test-pco-apart.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp5-rhythm.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp2-rhythm.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp3-rhythm.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-cp4-slurs.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-ly-rhythm.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-ly-key.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-ly-alter.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-ly-clef.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-repeat.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-tritone.mid" # Path and file name of imported midi file
Midi_file = "midi\GenCA2\test-gc.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-leaps.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-multiharm.mid" # Path and file name of imported midi file
#Midi_file = "midi\GenCA2\test-4th.mid" # Path and file name of imported midi file
